name: Publish to APT & Homebrew

on:
  #XXX-DELETEME release:
  #XXX-DELETEME   types: [released]
  # This workflow is reusable, i.e. it may be called from another workflow.
  # See https://docs.github.com/en/actions/using-workflows/reusing-workflows
  workflow_call:

jobs:
  xxx:
    runs-on: ubuntu-latest
    steps:
      - env:
          XXX: ${{ toJSON(github) }}
        run: echo $XXX
  # check-version:
  #   name: Check the version validity
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Check release validity
  #       run: bash .github/scripts/check-release.sh

  # debian:
  #   name: Publish Debian package
  #   runs-on: ubuntu-latest
  #   needs: check-version
  #   container:
  #     # Use ubuntu-18.04 to compile with glibc 2.27
  #     image: ubuntu:18.04
  #   steps:
  #   - name: Install needed dependencies
  #     run: |
  #       apt-get update && apt-get install -y curl
  #       apt-get install build-essential -y
  #   - uses: actions-rs/toolchain@v1
  #     with:
  #       toolchain: stable
  #       override: true
  #   - name: Install cargo-deb
  #     run: cargo install cargo-deb
  #   - uses: actions/checkout@v3
  #   - name: Build deb package
  #     run: cargo deb -p meilisearch -o target/debian/meilisearch.deb
  #   - name: Upload Debian package to release
  #     uses: svenstaro/upload-release-action@2.5.0
  #     with:
  #       repo_token: ${{ secrets.MEILI_BOT_GH_PAT }}
  #       file: target/debian/meilisearch.deb
  #       asset_name: meilisearch.deb
  #       tag: ${{ github.ref }}
  #   - name: Upload Debian package to apt repository
  #     run: curl -F package=@target/debian/meilisearch.deb https://${{ secrets.GEMFURY_PUSH_TOKEN }}@push.fury.io/meilisearch/

  # homebrew:
  #   name: Bump Homebrew formula
  #   runs-on: ubuntu-latest
  #   needs: check-version
  #   steps:
  #     - name: Create PR to Homebrew
  #       uses: mislav/bump-homebrew-formula-action@v2
  #       with:
  #         formula-name: meilisearch
  #       env:
  #         COMMITTER_TOKEN: ${{ secrets.HOMEBREW_COMMITTER_TOKEN }}
